package exception.rutimeexception.test;

public class RuntimeExceptionTest {
    public static void main(String[] args) {
        /**Arithmetic Exception
        int a=10, b=0;
        if(b!=0){
            int c = a/b;
            System.out.println(a);
        }
        else System.out.println("Infinity");

        --------------------------------*/

        /**Null Pointer Exception
        Object o = null;
        System.out.println(o.toString());

         -------------------------------*/

        /**Array Index Out of Bounds Exception
        int[] a = new int[2];
        System.out.println(a[2]);
        */
    }
}
